name: proj
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  
  # Location
  geolocator: ^13.0.1
  geocoding: ^3.0.0

  # Camera & Permissions
  camera: ^0.11.0+2
  permission_handler: ^11.3.1
  path_provider: ^2.1.4
  http: ^1.2.2
  image_picker: ^1.1.2

  # Firebase
  firebase_core: ^3.8.1
  cloud_firestore: ^5.5.0
  firebase_auth: ^5.7.0
  firebase_storage: ^12.4.10
  
  # Google Sign-In
  google_sign_in: ^6.2.1

  # AI
  google_generative_ai: ^0.4.3
  flutter_dotenv: ^5.1.0
  
  # State Management
  provider: ^6.1.2
  
  # Local Storage
  shared_preferences: ^2.2.2
  sqflite: ^2.3.0
  path: ^1.8.3

  # UI & Navigation
  cupertino_icons: ^1.0.8
  webview_flutter: ^4.13.0
  url_launcher: ^6.3.2
  app_links: ^6.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
   
  assets:
    - .env